#Preprocessing and Statistics

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

base = "/content/drive/MyDrive/anon/pidgindataset2026October/"

df = pd.read_csv(base+"root/Metadata1.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import re
import pandas as pd

def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # remove percentage signs explicitly
    text = text.replace("%", " ")

    # remove punctuation (.,!?;: etc.)
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [22]:
df["pidgin_transcription"] = df["pidgin_transcription"].apply(clean_text)
df["english_translation"] = df["english_translation"].apply(clean_text)

In [23]:
df.head()

,speaker_id,audio_path,pidgin_transcription,english_translation,medical_terms_english,medical_terms_pidgen,audio_length,sample_rate,num_channels,speech_rate,signal_to_noise_ratio,silence_ratio,audio,file_exists,text,reference,sample_id
0,Speaker_1,root/audio/Speaker_1/Speaker1-1.wav,e depend on your effort how you take dey do ex...,it all depends on your efforts regarding regul...,"['care', 'knee', 'walk', 'two days', 'one to t...","['exercise', 'everytime', 'after two day', 'no...",19.04,16000.0,1.0,2.678378,54.947548,0.319377,/content/drive/MyDrive/Brock_University/pidgin...,True,e depend on your effort how you take dey do ex...,e depend on your effort how you take dey do ex...,6a840a4ad1fd60283227
1,Speaker_1,root/audio/Speaker_1/Speaker1-2.wav,my daughter make four years two nights ago she...,my daughter is four years old two nights ago s...,"['daughter', 'four years old', 'vomited', 'sor...","['daughter', 'wake up', 'vomited', 'pain', 'ho...",34.48,16000.0,1.0,2.580879,53.953575,0.334655,/content/drive/MyDrive/Brock_University/pidgin...,True,my daughter make four years two nights ago she...,my daughter make four years two nights ago she...,fa777d58c8f323da62e2
2,Speaker_1,root/audio/Speaker_1/Speaker1-3.wav,hi dis na retention cyst e go need excise for ...,hi this is definitely a retention cyst it need...,"['retention cyst', 'mass', 'histopathological ...","['reasons', 'removed', 'important part of the ...",21.97,16000.0,1.0,2.321869,57.647476,0.335672,/content/drive/MyDrive/Brock_University/pidgin...,True,hi dis na retention cyst e go need excise for ...,hi dis na retention cyst e go need excise for ...,01fceaa9e74b77698df4
3,Speaker_1,root/audio/Speaker_1/Speaker1-4.wav,i be thirty one years woman and i get blod clo...,i am a thirty one year old woman with a blood ...,"['thirty one year old woman', 'head injury', '...","['thirty one years woman', 'not', 'head injury...",34.61,16000.0,1.0,2.571562,49.890247,0.308394,/content/drive/MyDrive/Brock_University/pidgin...,True,i be thirty one years woman and i get blod clo...,i be thirty one years woman and i get blod clo...,3d812380dee30f23b366
4,Speaker_1,root/audio/Speaker_1/Speaker1-5.wav,i be forty five years old man my platelet coun...,i am forty five years old male my platelet cou...,"['forty five years old male', 'platelet count'...","['forty five years old man', 'platelet count',...",42.63,16000.0,1.0,2.040783,50.834831,0.307166,/content/drive/MyDrive/Brock_University/pidgin...,True,i be forty five years old man my platelet coun...,i be forty five years old man my platelet coun...,ac3bdc92665cb5600166

In [24]:
import pandas as pd
import re
from collections import Counter

In [25]:
df["pidgin_transcription"] = df["pidgin_transcription"].astype(str).str.lower().str.strip()
df["english_translation"] = df["english_translation"].astype(str).str.lower().str.strip()

In [26]:
pidgin_words = df["pidgin_transcription"].apply(lambda x: x.split())

total_pidgin_words = pidgin_words.apply(len).sum()
unique_pidgin_words = len(set([w for words in pidgin_words for w in words]))

print("Total Pidgin Words:", total_pidgin_words)
print("Unique Pidgin Words:", unique_pidgin_words)

Total Pidgin Words: 662549
Unique Pidgin Words: 13209

In [27]:
ttr = unique_pidgin_words / total_pidgin_words
print("Type-Token Ratio (Pidgin):", round(ttr, 4))

Type-Token Ratio (Pidgin): 0.0199

In [28]:
pidgin_all_words = [w for words in pidgin_words for w in words]
pidgin_freq = Counter(pidgin_all_words)

top_pidgin_words = pd.DataFrame(
    pidgin_freq.most_common(30),
    columns=["word", "count"]
)

top_pidgin_words.head()

  word  count
0  dey  25985
1    i  22778
2  and  19796
3  the  16052
4  for  14711

In [29]:
df["pidgin_word_count"] = df["pidgin_transcription"].apply(lambda x: len(x.split()))
df["english_word_count"] = df["english_translation"].apply(lambda x: len(x.split()))

In [30]:
df.head()

,speaker_id,audio_path,pidgin_transcription,english_translation,medical_terms_english,medical_terms_pidgen,audio_length,sample_rate,num_channels,speech_rate,signal_to_noise_ratio,silence_ratio,audio,file_exists,text,reference,sample_id,pidgin_word_count,english_word_count
0,Speaker_1,root/audio/Speaker_1/Speaker1-1.wav,e depend on your effort how you take dey do ex...,it all depends on your efforts regarding regul...,"['care', 'knee', 'walk', 'two days', 'one to t...","['exercise', 'everytime', 'after two day', 'no...",19.04,16000.0,1.0,2.678378,54.947548,0.319377,/content/drive/MyDrive/Brock_University/pidgin...,True,e depend on your effort how you take dey do ex...,e depend on your effort how you take dey do ex...,6a840a4ad1fd60283227,51,34
1,Speaker_1,root/audio/Speaker_1/Speaker1-2.wav,my daughter make four years two nights ago she...,my daughter is four years old two nights ago s...,"['daughter', 'four years old', 'vomited', 'sor...","['daughter', 'wake up', 'vomited', 'pain', 'ho...",34.48,16000.0,1.0,2.580879,53.953575,0.334655,/content/drive/MyDrive/Brock_University/pidgin...,True,my daughter make four years two nights ago she...,my daughter make four years two nights ago she...,fa777d58c8f323da62e2,89,136
2,Speaker_1,root/audio/Speaker_1/Speaker1-3.wav,hi dis na retention cyst e go need excise for ...,hi this is definitely a retention cyst it need...,"['retention cyst', 'mass', 'histopathological ...","['reasons', 'removed', 'important part of the ...",21.97,16000.0,1.0,2.321869,57.647476,0.335672,/content/drive/MyDrive/Brock_University/pidgin...,True,hi dis na retention cyst e go need excise for ...,hi dis na retention cyst e go need excise for ...,01fceaa9e74b77698df4,51,56
3,Speaker_1,root/audio/Speaker_1/Speaker1-4.wav,i be thirty one years woman and i get blod clo...,i am a thirty one year old woman with a blood ...,"['thirty one year old woman', 'head injury', '...","['thirty one years woman', 'not', 'head injury...",34.61,16000.0,1.0,2.571562,49.890247,0.308394,/content/drive/MyDrive/Brock_University/pidgin...,True,i be thirty one years woman and i get blod clo...,i be thirty one years woman and i get blod clo...,3d812380dee30f23b366,89,94
4,Speaker_1,root/audio/Speaker_1/Speaker1-5.wav,i be forty five years old man my platelet coun...,i am forty five years old male my platelet cou...,"['forty five years old male', 'platelet count'...","['forty five years old man', 'platelet count',...",42.63,16000.0,1.0,2.040783,50.834831,0.307166,/content/drive/MyDrive/Brock_University/pidgin...,True,i be forty five years old man my platelet coun...,i be forty five years old man my platelet coun...,ac3bdc92665cb5600166,87,81

In [31]:
df["length_ratio"] = df["pidgin_word_count"] / df["english_word_count"]

print("Average Length Ratio:", round(df["length_ratio"].mean(), 3))

Average Length Ratio: 1.006

In [32]:
df[df["english_word_count"] == 0][
    ["english_translation", "pidgin_transcription", "english_word_count", "pidgin_word_count"]
]

Empty DataFrame
Columns: [english_translation, pidgin_transcription, english_word_count, pidgin_word_count]
Index: []

In [33]:
bad_samples = df[
    (df["audio_length"].isna()) | (df["audio_length"] == 0)
]

print("Number of bad samples:", len(bad_samples))

bad_samples[["speaker_id", "audio_path", "audio_length"]].head()

Number of bad samples: 0

Empty DataFrame
Columns: [speaker_id, audio_path, audio_length]
Index: []

In [34]:
df = df[
    (df["audio_length"].notna()) & (df["audio_length"] > 2)
].copy()

In [35]:
df = df[
    (df["english_word_count"].notna()) &
    (df["english_word_count"] > 0)
].copy()

In [36]:
df.pidgin_transcription.count()

np.int64(10218)

In [37]:
df.head()

,speaker_id,audio_path,pidgin_transcription,english_translation,medical_terms_english,medical_terms_pidgen,audio_length,sample_rate,num_channels,speech_rate,signal_to_noise_ratio,silence_ratio,audio,file_exists,text,reference,sample_id,pidgin_word_count,english_word_count,length_ratio
0,Speaker_1,root/audio/Speaker_1/Speaker1-1.wav,e depend on your effort how you take dey do ex...,it all depends on your efforts regarding regul...,"['care', 'knee', 'walk', 'two days', 'one to t...","['exercise', 'everytime', 'after two day', 'no...",19.04,16000.0,1.0,2.678378,54.947548,0.319377,/content/drive/MyDrive/Brock_University/pidgin...,True,e depend on your effort how you take dey do ex...,e depend on your effort how you take dey do ex...,6a840a4ad1fd60283227,51,34,1.500000
1,Speaker_1,root/audio/Speaker_1/Speaker1-2.wav,my daughter make four years two nights ago she...,my daughter is four years old two nights ago s...,"['daughter', 'four years old', 'vomited', 'sor...","['daughter', 'wake up', 'vomited', 'pain', 'ho...",34.48,16000.0,1.0,2.580879,53.953575,0.334655,/content/drive/MyDrive/Brock_University/pidgin...,True,my daughter make four years two nights ago she...,my daughter make four years two nights ago she...,fa777d58c8f323da62e2,89,136,0.654412
2,Speaker_1,root/audio/Speaker_1/Speaker1-3.wav,hi dis na retention cyst e go need excise for ...,hi this is definitely a retention cyst it need...,"['retention cyst', 'mass', 'histopathological ...","['reasons', 'removed', 'important part of the ...",21.97,16000.0,1.0,2.321869,57.647476,0.335672,/content/drive/MyDrive/Brock_University/pidgin...,True,hi dis na retention cyst e go need excise for ...,hi dis na retention cyst e go need excise for ...,01fceaa9e74b77698df4,51,56,0.910714
3,Speaker_1,root/audio/Speaker_1/Speaker1-4.wav,i be thirty one years woman and i get blod clo...,i am a thirty one year old woman with a blood ...,"['thirty one year old woman', 'head injury', '...","['thirty one years woman', 'not', 'head injury...",34.61,16000.0,1.0,2.571562,49.890247,0.308394,/content/drive/MyDrive/Brock_University/pidgin...,True,i be thirty one years woman and i get blod clo...,i be thirty one years woman and i get blod clo...,3d812380dee30f23b366,89,94,0.946809
4,Speaker_1,root/audio/Speaker_1/Speaker1-5.wav,i be forty five years old man my platelet coun...,i am forty five years old male my platelet cou...,"['forty five years old male', 'platelet count'...","['forty five years old man', 'platelet count',...",42.63,16000.0,1.0,2.040783,50.834831,0.307166,/content/drive/MyDrive/Brock_University/pidgin...,True,i be forty five years old man my platelet coun...,i be forty five years old man my platelet coun...,ac3bdc92665cb5600166,87,81,1.074074

In [38]:
df.isnull().sum()

speaker_id               0
audio_path               0
pidgin_transcription     0
english_translation      0
medical_terms_english    0
medical_terms_pidgen     0
audio_length             0
sample_rate              0
num_channels             0
speech_rate              0
signal_to_noise_ratio    0
silence_ratio            0
audio                    0
file_exists              0
text                     0
reference                0
sample_id                0
pidgin_word_count        0
english_word_count       0
length_ratio             0
dtype: int64

In [39]:
df.isnull().values.any()

np.False_

In [40]:
df.isnull().sum().sum()

np.int64(0)

In [41]:
null_rows = df[df.isnull().any(axis=1)]

print("Rows with null values:", len(null_rows))
null_rows.head()

Rows with null values: 0

Empty DataFrame
Columns: [speaker_id, audio_path, pidgin_transcription, english_translation, medical_terms_english, medical_terms_pidgen, audio_length, sample_rate, num_channels, speech_rate, signal_to_noise_ratio, silence_ratio, audio, file_exists, text, reference, sample_id, pidgin_word_count, english_word_count, length_ratio]
Index: []

In [42]:
df = df.dropna().copy()

df = df[
    (df["english_translation"].str.strip() != "") &
    (df["pidgin_transcription"].str.strip() != "")
].copy()

In [43]:
df.pidgin_transcription.count()

np.int64(10218)

In [44]:
total_hours = df["audio_length"].sum() / 3600
total_utterances = len(df)
num_speakers = df["speaker_id"].nunique()

num_english_words = df["english_translation"].apply(lambda x: len(str(x).split())).sum()
num_pidgin_words = df["pidgin_transcription"].apply(lambda x: len(str(x).split())).sum()

print("Total Hours:", round(total_hours, 2))
print("Total Utterances:", total_utterances)
print("Number of Speakers:", num_speakers)
print("English Words:", num_english_words)
print("Pidgin Words:", num_pidgin_words)

Total Hours: 78.98
Total Utterances: 10218
Number of Speakers: 21
English Words: 665329
Pidgin Words: 662549

In [45]:
features = ["speech_rate", "signal_to_noise_ratio", "silence_ratio"]

audio_stats = df[features].describe()
print(audio_stats)

        speech_rate  signal_to_noise_ratio  silence_ratio
count  10218.000000           10218.000000   10218.000000
mean       2.363408              32.039383       0.187849
std        0.492410              10.505199       0.111876
min        0.132050               5.822312       0.000000
25%        2.029071              25.182662       0.120457
50%        2.346576              30.804038       0.187444
75%        2.685537              37.089207       0.259174
max       14.694917              65.283104       0.971912

In [46]:
summary = {
    "Speech Rate (words/sec)": df["speech_rate"].agg(["mean","std","min","max"]),
    "SNR (dB)": df["signal_to_noise_ratio"].agg(["mean","std","min","max"]),
    "Silence Ratio": df["silence_ratio"].agg(["mean","std","min","max"])
}

summary_df = pd.DataFrame(summary).T.round(3)
print(summary_df)

                           mean     std    min     max
Speech Rate (words/sec)   2.363   0.492  0.132  14.695
SNR (dB)                 32.039  10.505  5.822  65.283
Silence Ratio             0.188   0.112  0.000   0.972

In [47]:
corr_matrix = df[features].corr()
print(corr_matrix)

                       speech_rate  signal_to_noise_ratio  silence_ratio
speech_rate               1.000000              -0.192559      -0.359004
signal_to_noise_ratio    -0.192559               1.000000       0.689541
silence_ratio            -0.359004               0.689541       1.000000

In [48]:
speaker_stats = df.groupby("speaker_id")[features].mean().round(3)
print(speaker_stats)

            speech_rate  signal_to_noise_ratio  silence_ratio
speaker_id
Speaker_1         2.328                 51.654          0.301
Speaker_10        2.612                 32.513          0.173
Speaker_11        1.966                 26.718          0.147
Speaker_12        2.186                 34.424          0.227
Speaker_13        2.532                 31.437          0.203
Speaker_14        2.373                 26.522          0.168
Speaker_15        2.107                 33.642          0.239
Speaker_16        2.491                 30.492          0.224
Speaker_17        2.188                 19.117          0.042
Speaker_18        2.559                 26.369          0.126
Speaker_19        2.154                 30.809          0.179
Speaker_2         2.451                 33.912          0.176
Speaker_20        2.395                 28.690          0.115
Speaker_21        1.942                 33.891          0.353
Speaker_3         2.215                 34.157          0.226
Speaker_4         2.291                 54.266          0.307
Speaker_5         1.894                 32.691          0.200
Speaker_6         2.838                 24.238          0.129
Speaker_7         2.805                 20.517          0.050
Speaker_8         2.517                 27.759          0.127
Speaker_9         2.715                 32.359          0.158

In [49]:
df.to_csv(base+"metadata_version2.0.csv", index=False)

#Linguistic Analysis

In [50]:
import pandas as pd
import re
from collections import Counter

In [51]:
df["pidgin_transcription"] = df["pidgin_transcription"].astype(str).str.lower().str.strip()
df["english_translation"] = df["english_translation"].astype(str).str.lower().str.strip()

In [52]:
df.head()

,speaker_id,audio_path,pidgin_transcription,english_translation,medical_terms_english,medical_terms_pidgen,audio_length,sample_rate,num_channels,speech_rate,signal_to_noise_ratio,silence_ratio,audio,file_exists,text,reference,sample_id,pidgin_word_count,english_word_count,length_ratio
0,Speaker_1,root/audio/Speaker_1/Speaker1-1.wav,e depend on your effort how you take dey do ex...,it all depends on your efforts regarding regul...,"['care', 'knee', 'walk', 'two days', 'one to t...","['exercise', 'everytime', 'after two day', 'no...",19.04,16000.0,1.0,2.678378,54.947548,0.319377,/content/drive/MyDrive/Brock_University/pidgin...,True,e depend on your effort how you take dey do ex...,e depend on your effort how you take dey do ex...,6a840a4ad1fd60283227,51,34,1.500000
1,Speaker_1,root/audio/Speaker_1/Speaker1-2.wav,my daughter make four years two nights ago she...,my daughter is four years old two nights ago s...,"['daughter', 'four years old', 'vomited', 'sor...","['daughter', 'wake up', 'vomited', 'pain', 'ho...",34.48,16000.0,1.0,2.580879,53.953575,0.334655,/content/drive/MyDrive/Brock_University/pidgin...,True,my daughter make four years two nights ago she...,my daughter make four years two nights ago she...,fa777d58c8f323da62e2,89,136,0.654412
2,Speaker_1,root/audio/Speaker_1/Speaker1-3.wav,hi dis na retention cyst e go need excise for ...,hi this is definitely a retention cyst it need...,"['retention cyst', 'mass', 'histopathological ...","['reasons', 'removed', 'important part of the ...",21.97,16000.0,1.0,2.321869,57.647476,0.335672,/content/drive/MyDrive/Brock_University/pidgin...,True,hi dis na retention cyst e go need excise for ...,hi dis na retention cyst e go need excise for ...,01fceaa9e74b77698df4,51,56,0.910714
3,Speaker_1,root/audio/Speaker_1/Speaker1-4.wav,i be thirty one years woman and i get blod clo...,i am a thirty one year old woman with a blood ...,"['thirty one year old woman', 'head injury', '...","['thirty one years woman', 'not', 'head injury...",34.61,16000.0,1.0,2.571562,49.890247,0.308394,/content/drive/MyDrive/Brock_University/pidgin...,True,i be thirty one years woman and i get blod clo...,i be thirty one years woman and i get blod clo...,3d812380dee30f23b366,89,94,0.946809
4,Speaker_1,root/audio/Speaker_1/Speaker1-5.wav,i be forty five years old man my platelet coun...,i am forty five years old male my platelet cou...,"['forty five years old male', 'platelet count'...","['forty five years old man', 'platelet count',...",42.63,16000.0,1.0,2.040783,50.834831,0.307166,/content/drive/MyDrive/Brock_University/pidgin...,True,i be forty five years old man my platelet coun...,i be forty five years old man my platelet coun...,ac3bdc92665cb5600166,87,81,1.074074

In [53]:
pidgin_words = df["pidgin_transcription"].apply(lambda x: x.split())

total_pidgin_words = pidgin_words.apply(len).sum()
unique_pidgin_words = len(set([w for words in pidgin_words for w in words]))

print("Total Pidgin Words:", total_pidgin_words)
print("Unique Pidgin Words:", unique_pidgin_words)

Total Pidgin Words: 662549
Unique Pidgin Words: 13209

In [54]:
ttr = unique_pidgin_words / total_pidgin_words
print("Type-Token Ratio (Pidgin):", round(ttr, 4))

Type-Token Ratio (Pidgin): 0.0199

In [55]:
pidgin_all_words = [w for words in pidgin_words for w in words]
pidgin_freq = Counter(pidgin_all_words)

top_pidgin_words = pd.DataFrame(
    pidgin_freq.most_common(30),
    columns=["word", "count"]
)

top_pidgin_words.head()

  word  count
0  dey  25985
1    i  22778
2  and  19796
3  the  16052
4  for  14711

In [56]:
df["pidgin_word_count"] = df["pidgin_transcription"].apply(lambda x: len(x.split()))
df["english_word_count"] = df["english_translation"].apply(lambda x: len(x.split()))

In [57]:
df["length_ratio"] = df["pidgin_word_count"] / df["english_word_count"]

print("Average Length Ratio:", round(df["length_ratio"].mean(), 3))

Average Length Ratio: 1.006

In [58]:
pidgin_vocab = set(pidgin_all_words)
english_vocab = set([w for x in df["english_translation"] for w in x.split()])

overlap = pidgin_vocab.intersection(english_vocab)

print("Pidgin vocab size:", len(pidgin_vocab))
print("English vocab size:", len(english_vocab))
print("Shared vocabulary:", len(overlap))

Pidgin vocab size: 13209
English vocab size: 14811
Shared vocabulary: 12033

#Code-Switching Annotations

In [ ]:
import re
import pandas as pd
from collections import Counter

# Column name
pidgin_col = "pidgin_transcription"

def tokenize(text):
    if pd.isna(text):
        return []

    text = str(text).lower()
    text = re.sub(r"[^a-zA-Z\s]", " ", text)  # remove punctuation/numbers
    text = re.sub(r"\s+", " ", text).strip()

    return text.split()

# tokenize all pidgin transcriptions
df["pidgin_tokens"] = df[pidgin_col].apply(tokenize)

# flatten tokens
all_tokens = [token for tokens in df["pidgin_tokens"] for token in tokens]

# count frequency
token_counts = Counter(all_tokens)

# create unique token dataset
token_df = pd.DataFrame(
    token_counts.items(),
    columns=["token", "frequency"]
)

# sort by frequency
token_df = token_df.sort_values("frequency", ascending=False).reset_index(drop=True)

# add annotation columns
token_df["language_label"] = ""   # e.g., Pidgin / English / Ambiguous / Other
token_df["notes"] = ""

token_df.head()

  token  frequency language_label notes
0   dey      13762
1     i      11124
2   and      10074
3   the       7978
4   for       7255

In [ ]:
df.to_csv(base+"metadata_version2.0.csv", index=False)